networks:
  app_network:
    driver: bridge

services:
  weather-service:
    build: ./weather_service
    container_name: weather_service
    networks:
      - app_network
    ports:
      - "$WEATHER_SERVICE_HOST_PORT:8000"

  ui-service:
    build: ./ui_service
    container_name: ui_service
    depends_on:
      - weather-service
    networks:
      - app_network
    environment:
      - WEATHER_API_URL=http://weather-service:8000
    ports:
      - "$DASHBOARD_HOST_PORT:8000"